/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpu;

/**
 *
 * @author user
 */
import Items.Job;
import Items.Queue;
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class UserData extends javax.swing.JFrame {

    /**
     * Creates new form UserData
     */
    public UserData() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        processBttn = new javax.swing.JButton();
        DefaultBttn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField1.setText("0");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(230, 290, 50, 20);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField2.setText("0");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(330, 290, 50, 20);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField3.setText("0");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(430, 290, 50, 20);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField4.setText("0");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(230, 320, 50, 20);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField6.setText("0");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(430, 320, 50, 20);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField7.setText("0");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(230, 350, 50, 20);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField9.setText("0");
        jPanel1.add(jTextField9);
        jTextField9.setBounds(430, 380, 50, 20);

        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField10.setText("0");
        jPanel1.add(jTextField10);
        jTextField10.setBounds(230, 380, 50, 20);

        jTextField11.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField11.setText("0");
        jPanel1.add(jTextField11);
        jTextField11.setBounds(230, 410, 50, 20);

        jTextField12.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField12.setText("0");
        jPanel1.add(jTextField12);
        jTextField12.setBounds(230, 440, 50, 20);

        jTextField13.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField13.setText("0");
        jPanel1.add(jTextField13);
        jTextField13.setBounds(230, 470, 50, 20);

        jTextField15.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField15.setText("0");
        jPanel1.add(jTextField15);
        jTextField15.setBounds(330, 380, 50, 20);

        jTextField18.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField18.setText("0");
        jPanel1.add(jTextField18);
        jTextField18.setBounds(430, 350, 50, 20);

        jTextField19.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField19.setText("0");
        jPanel1.add(jTextField19);
        jTextField19.setBounds(430, 410, 50, 20);

        jTextField20.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField20.setText("0");
        jPanel1.add(jTextField20);
        jTextField20.setBounds(430, 440, 50, 20);

        jTextField21.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField21.setText("0");
        jPanel1.add(jTextField21);
        jTextField21.setBounds(330, 470, 50, 20);

        jTextField24.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField24.setText("0");
        jPanel1.add(jTextField24);
        jTextField24.setBounds(430, 500, 50, 20);

        jTextField25.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField25.setText("0");
        jPanel1.add(jTextField25);
        jTextField25.setBounds(330, 410, 50, 20);

        jTextField16.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField16.setText("0");
        jPanel1.add(jTextField16);
        jTextField16.setBounds(330, 440, 50, 20);

        jTextField17.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField17.setText("0");
        jPanel1.add(jTextField17);
        jTextField17.setBounds(330, 500, 50, 20);

        jTextField22.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField22.setText("0");
        jPanel1.add(jTextField22);
        jTextField22.setBounds(230, 500, 50, 20);

        jTextField14.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField14.setText("0");
        jPanel1.add(jTextField14);
        jTextField14.setBounds(330, 320, 50, 20);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField5.setText("0");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(330, 350, 50, 20);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jTextField8.setText("0");
        jPanel1.add(jTextField8);
        jTextField8.setBounds(430, 470, 50, 20);

        processBttn.setText("Process");
        processBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBttnActionPerformed(evt);
            }
        });
        jPanel1.add(processBttn);
        processBttn.setBounds(400, 560, 90, 23);

        DefaultBttn.setText("Default Input");
        DefaultBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultBttnActionPerformed(evt);
            }
        });
        jPanel1.add(DefaultBttn);
        DefaultBttn.setBounds(230, 560, 110, 23);

        jLabel16.setText("P8");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(150, 500, 40, 14);

        jLabel15.setText("P7");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(150, 470, 30, 14);

        jLabel14.setText("P6");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(150, 440, 30, 14);

        jLabel13.setText("P5");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(150, 410, 30, 14);

        jLabel12.setText("P4");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 380, 30, 14);

        jLabel11.setText("P3");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(150, 350, 30, 14);

        jLabel10.setText("P2");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 320, 30, 14);

        jLabel9.setText("P1");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 290, 30, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Priority");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 270, 50, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Burst");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 270, 50, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Arrival");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 270, 50, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("0<=Arrive<30 & 0<Burst<13 & 0<Prioroty<127");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 200, 310, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Please insert the process data");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 170, 160, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("User Input Data");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 90, 140, 50);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Simulation of Process Scheduling");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 30, 360, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\simulation9.jfif")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DefaultBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultBttnActionPerformed
        jTextField1.setText("0");
        jTextField2.setText("1");
        jTextField3.setText("59");
        jTextField4.setText("26");
        jTextField5.setText("3");
        jTextField6.setText("35");
        jTextField7.setText("16");
        jTextField8.setText("64");
        jTextField9.setText("75");
        jTextField10.setText("18");
        jTextField11.setText("7");
        jTextField12.setText("11");
        jTextField13.setText("24");
        jTextField14.setText("8");
        jTextField15.setText("13");
        jTextField16.setText("26");
        jTextField17.setText("10");
        jTextField18.setText("41");
        jTextField19.setText("53");
        jTextField20.setText("77");
        jTextField21.setText("9");
        jTextField22.setText("15");
        jTextField25.setText("6");
        jTextField24.setText("47");       // TODO add your handling code here:
    }//GEN-LAST:event_DefaultBttnActionPerformed

    private void processBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBttnActionPerformed
     fillJobList();
        Interface1 interface1 = new Interface1();  // create new object of the main frame
        interface1.setAssignedQueue(new Queue(list));  // add list of jobs to the main queue
        interface1.show();
        this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_processBttnActionPerformed
private ArrayList<Job> list = new ArrayList<Job>(); // list of jobs entered by the user
    private int [] userData = new int [24];  // data entered by the user
    private int fillJobList()
    {
        getData(); // collect data from the frame
        for(int i=0 ; i<8 ; i++)
        {
            int arriveTime = userData[i*3];
            int burstTime = userData[(i*3)+1];
            int priority = userData[(i*3)+2];
            if(checkJob(arriveTime,burstTime,priority ))
            {
               list.add(new Job(i+1, arriveTime, burstTime, priority));
            }
        }
        return 0;
    }
    private boolean checkJob(int arrive , int burst , int priority)
    {
        if( arrive < 0  || arrive > 30 ) {return false;}
        if( burst <= 0 || burst > 13 ) {return false;}
        if( priority <=0  || priority > 127) {return false;}
        return true;
    }
       
    /**
     * get the data from the frame and put it in an array
     */
    private void getData ()
    {
        try {
        userData[0] = Integer.parseInt(jTextField1.getText());
        userData[1] = Integer.parseInt(jTextField2.getText());
        userData[2] = Integer.parseInt(jTextField3.getText());
        userData[3] = Integer.parseInt(jTextField4.getText());
        userData[4] = Integer.parseInt(jTextField14.getText());
        userData[5] = Integer.parseInt(jTextField6.getText());
        userData[6] = Integer.parseInt(jTextField7.getText());
        userData[7] = Integer.parseInt(jTextField5.getText());
        userData[8] = Integer.parseInt(jTextField18.getText());
        userData[9] = Integer.parseInt(jTextField10.getText());
        userData[10] = Integer.parseInt(jTextField15.getText());
        userData[11] = Integer.parseInt(jTextField19.getText());
        userData[12] = Integer.parseInt(jTextField11.getText());
        userData[13] = Integer.parseInt(jTextField25.getText());
        userData[14] = Integer.parseInt(jTextField19.getText());
        userData[15] = Integer.parseInt(jTextField12.getText());
        userData[16] = Integer.parseInt(jTextField16.getText());
        userData[17] = Integer.parseInt(jTextField20.getText());
        userData[18] = Integer.parseInt(jTextField13.getText());
        userData[19] = Integer.parseInt(jTextField21.getText());
        userData[20] = Integer.parseInt(jTextField8.getText());
        userData[21] = Integer.parseInt(jTextField22.getText());
        userData[22] = Integer.parseInt(jTextField17.getText());
        userData[23] = Integer.parseInt(jTextField24.getText()); 
        }
        catch (Exception e)  // insufficeint input will trigger an error message
        { JOptionPane.showMessageDialog( null , "Insufficient input" , "Error" , ERROR); }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DefaultBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton processBttn;
    // End of variables declaration//GEN-END:variables
}
